## EXPERIMENT SPECIFIC
[experiment]

start_date = "2024-02-27"

enrollment_end_date = "2024-03-08"



[experiment.exposure_signal]
name = "nimbus_exposure"
friendly_name = "Nimbus Exposure"
description = "users who browsed in private mode"
data_source = "open_private_mode"
select_expression = "exposure_date is not null"


[data_sources.open_private_mode]
from_expression = """
    (
  SELECT events.client_info.client_id
        , MIN(DATE(events.submission_timestamp )) exposure_date
  FROM `mozdata.firefox_ios.events_unnested`  AS events
  CROSS JOIN UNNEST(events.event_extra) AS ext
  WHERE ((events.event_category  = 'tabs_tray' AND events.event_name = 'private_browsing_icon_tapped')
          OR
          (events.event_category = 'preferences' AND events.event_name = 'private_browsing_button_tapped' AND ext.value = 'true')
        )
    AND events.normalized_channel  = 'release'
    AND  DATE(events.submission_timestamp) BETWEEN "2024-02-27" AND "2024-03-08"
    group by 1
    )
    """
submission_date_column = "exposure_date"

#[metrics]

#overall = ['serp_ad_clicks_lm', 'search_count_lm', 'active_hours_lm', 'days_of_use_lm']
#weekly = ['serp_ad_clicks_lm', 'search_count_lm', 'active_hours_lm', 'days_of_use_lm']

#[metrics.serp_ad_clicks_lm]
#friendly_name = "Ad Clicks"
#description = "Number of ad clicks on a search engine results page."
#select_expression = "{{agg_sum('ad_click')}}"
#data_source = "mobile_search_clients_engines_sources_daily"

[metrics.serp_ad_clicks.statistics.bootstrap_mean_linear_model]
[metrics.serp_ad_clicks.statistics.bootstrap_mean_linear_model.covariate_adjustment]
metric = 'serp_ad_clicks'
period = 'preenrollment_week'



[metrics.search_count.statistics.bootstrap_mean_linear_model]
[metrics.search_count.statistics.bootstrap_mean_linear_model.covariate_adjustment]
metric = 'search_count'
period = 'preenrollment_week'


[metrics.active_hours.statistics.bootstrap_mean_linear_model]
[metrics.active_hours.statistics.bootstrap_mean_linear_model.covariate_adjustment]
metric = 'active_hours'
period = 'preenrollment_week'

[metrics.days_of_use.statistics.bootstrap_mean_linear_model]
drop_highest = 0.0
[metrics.days_of_use.statistics.bootstrap_mean_linear_model.covariate_adjustment]
metric = 'days_of_use'
period = 'preenrollment_week'

